var angular = require('angular');
var _ = require("lodash");
require('angular-route');
require('./hz-service');
require('./services/persons-repo');
require('./services/experiments-repo');
require('./app');
require('./controllers/home-controller');
require('./controllers/experiments-controller');
require('./controllers/search-controller');
require('./controllers/teams-controller');
require('bootstrap-loader');
require('../css/app.css');
